### ISSUE TITLE
Consider including plain-text versions of PROSPECT coefficients

### ISSUE THREAD

**Issue by ashiklom** [jbferet/prospect#4]
(Comment as part of JOSS review: https://github.com/openjournals/joss-reviews/issues/6027)

I think the typical best practice for R packages is to include plain-text versions of internal package data and the code used to convert them into the internal data. Here's the [relevant discussion in Writing R Packages](https://r-pkgs.org/data.html#sec-data-sysdata). In the context of this package, you might consider also including plain-text versions of the PROSPECT absorption coefficients and refractive index and the code used to put these into the final PROSPECT input data frame (which is stored in binary representation in the package). Among other things, this will (1) allow you to version-control the PROSPECT coefficients in human-readable git fashion (e.g., in case the calibrations change in the future), and (2) make the package resilient to changes in the binary encoding of `Rdata` and `rda` files.

This is **not** a requirement for my review; just a friendly suggestion!

**Comment by jbferet** [comment]
thank you @ashiklom for the suggestion!
The next update will follow this recommendation.

**Comment by jbferet** [comment]
prospect v1.5.0 now includes additional information in the 'data-raw' directory: 

1. [dataSpec_PRO.txt](https://github.com/jbferet/prospect/blob/master/data-raw/dataSpec_PRO.txt) includes the refractive index, specific absorption coefficients for each constituent, and corresponding wavelength with 1 nm sampling. 

2. [create_sysdata.R](https://github.com/jbferet/prospect/blob/master/data-raw/create_sysdata.R) is the R script generating the variable _SpecPROSPECT_FullRange_, and the variable _OptDomain_RT_, available when loading the package.

- SpecPROSPECT_FullRange includes refractive index and specific absorption coefficient from dataSpec_PRO.txt, as well as the transmissivity computed with the function calctav for two angles, 40 degrees and 90 degrees. User can still choose another angle with the alpha parameter, then calctav will run instead of using the default transmissivity for an angle of 40 degrees (and thank you for the suggestion, it speeds up the computation, indeed!)
- OptDomain_RT includes optimal spectral domains defined in [Féret et al.(2019)](https://doi.org/10.1016/j.rse.2018.11.002)) and (Spafford et al. (2021))[https://doi.org/10.1016/j.rse.2020.112176]
